---
title: 'Open Science: A Zealot's View'
author: "Jeff W. Hollister"
date: "3/25/2015"
output: word_document
keywords: ["open science","open source","open access","open data","twitter","github","reproducible research"]
---

Open science encompasses many concepts, but most agree that for science to be open four things must be true. First, all components of the scientific project must be freely available including manuscripts, code, and data.  Second, others must be able to repeat your work and reproduce the results.  Third, open science is a product of the internet age and thus needs to be web enabled.  Lastly, opening ones science is expected to be a process, not an event.  In this talk, I am going to address each of these components, but this will be almost entirely from my own perspective. I will discuss how I have progressively opened up my science, the benefits to doing that, and describe the tools I have used.  In this last part, I will focus on the importance of the web, in particular social media, and how I have used open source geospatial tools.  My goals for this talk are to use my evolution into an open science zealot as a means to show examples and provide the motivation for others to begin utilizing these same tools in there research. 


